#!/bin/bash -x

tinygo build -size short -o ./build/test.hex -target=wioterminal ./examples/net/http-get
tinygo build -size short -o ./build/test.hex -target=pyportal ./examples/net/http-head
tinygo build -size short -o ./build/test.hex -target=nano-rp2040 ./examples/net/http-post
tinygo build -size short -o ./build/test.hex -target=metro-m4-airlift ./examples/net/http-postform
tinygo build -size short -o ./build/test.hex -target=matrixportal-m4 ./examples/net/mqttclient/paho
tinygo build -size short -o ./build/test.hex -target=wioterminal ./examples/net/ntpclient
tinygo build -size short -o ./build/test.hex -target=arduino-nano33 ./examples/net/socket
tinygo build -size short -o ./build/test.hex -target=pyportal ./examples/net/tcpclient
tinygo build -size short -o ./build/test.hex -target=nano-rp2040 ./examples/net/tcpecho
tinygo build -size short -o ./build/test.hex -target=metro-m4-airlift ./examples/net/tlsclient
tinygo build -size short -o ./build/test.hex -target=matrixportal-m4 ./examples/net/webclient
tinygo build -size short -o ./build/test.hex -target=wioterminal ./examples/net/webclient-tinyterm
tinygo build -size short -o ./build/test.hex -target=pyportal ./examples/net/webserver
tinygo build -size short -o ./build/test.hex -target=nano-rp2040 ./examples/net/websocket/dial
tinygo build -size short -o ./build/test.hex -target=metro-m4-airlift ./examples/net/websocket/handler
tinygo build -size short -o ./build/test.hex -target=pyportal ./examples/net/webstatic
tinygo build -size short -o ./build/test.hex -target=challenger-rp2040 ./examples/net/tcpclient
